"""Step 6 — Methodology, limitations, and legal boundaries."""

import streamlit as st

st.set_page_config(page_title="Methodology — ForkFund", layout="wide")

st.title("Methodology & Limitations")
st.caption("How ForkFund works — and what it does not do")

st.markdown("---")

st.subheader("Synthetic Data")
st.markdown(
    """
    All restaurant, transaction, POS, and lender data in ForkFund is **computer-generated**.

    - The `src/utils/data_generator.py` module produces 150–200 fictional restaurants and
      their associated financial records using configurable statistical distributions.
    - No real company names, tax numbers, bank accounts, or transaction histories are used.
    - CSV files in `data/synthetic/` are regenerated by running the data generator and are
      committed to the repository for reproducibility.

    **Why synthetic data?**
    Using real restaurant data in a student MVP would raise significant GDPR, data-sharing,
    and consent obligations. Synthetic data lets us demonstrate the full platform concept
    without any of those risks.
    """
)

st.markdown("---")

st.subheader("Scoring Methodology")
st.markdown(
    """
    ForkFund produces a **credit score from 0 to 100** based on five weighted dimensions:

    | Dimension | Weight | Source |
    |-----------|--------|--------|
    | Revenue stability | 25 % | PSD2 / POS data |
    | Cash flow health | 25 % | PSD2 data |
    | Debt-to-revenue ratio | 20 % | Accounting data |
    | Business longevity | 15 % | KvK registration |
    | KvK compliance | 15 % | KvK registration |

    Each sub-score is independently normalised to [0, 100] before weighting. The final score
    is a weighted average. Sub-scores are surfaced individually to make the assessment
    **transparent and explainable**.

    The weights above are illustrative starting values. They are not derived from historical
    default data and do not represent a validated credit model.
    """
)

st.markdown("---")

st.subheader("Simulated Integrations")
st.markdown(
    """
    ForkFund simulates the following data integrations:

    | Integration | Real-world equivalent | In ForkFund |
    |-------------|-----------------------|-------------|
    | PSD2 / Open Banking | Tink, Nordigen, Salt Edge | CSV with synthetic bank transactions |
    | POS System | Square, Lightspeed, Untill | CSV with synthetic daily revenue |
    | Accounting | Exact, Twinfield, Moneybird | CSV with synthetic P&L figures |
    | KvK | Dutch Chamber of Commerce API | CSV with synthetic company records |

    Clicking "Connect" in the Data Connection step simulates the OAuth / consent flow
    that a real integration would require. No network request is made.
    """
)

st.markdown("---")

st.subheader("Limitations")
st.markdown(
    """
    ForkFund has the following known limitations by design:

    1. **Synthetic data only** — results have no predictive validity for real restaurants.
    2. **No longitudinal validation** — the scoring model has not been backtested against
       actual loan default rates.
    3. **Static lender data** — lender profiles are fictional and do not reflect real
       institutions, their criteria, or their current products.
    4. **No regulatory compliance** — ForkFund has not been reviewed against MiFID II,
       the EU AI Act, CRD IV, or any lending regulation.
    5. **Single-session state** — data entered is stored only in Streamlit session state
       and is lost on page refresh. There is no persistence layer.
    6. **No multi-user support** — the MVP is single-user and single-session by design.
    """
)

st.markdown("---")

st.subheader("Why This Is Not Real Underwriting")
st.markdown(
    """
    Real credit underwriting involves:

    - Verified identity checks (KYC/AML) against live government databases
    - Consent-based access to live bank account data via regulated PSD2 APIs
    - Actuarial models trained on historical default and repayment data
    - Regulatory approval and licensing (e.g., credit intermediary or lender licence)
    - Human review, appeals processes, and adverse-action notices

    ForkFund does **none** of these things. It is a conceptual demonstration of what a
    credit-intelligence layer could look like — not a working implementation of one.
    """
)

st.markdown("---")

st.subheader("Legal Boundaries")
st.markdown(
    """
    > This application does not provide financial advice, credit decisions, or any regulated
    > financial service. It is a student prototype for educational and demonstration purposes
    > only. No data entered into this application is transmitted, stored permanently, or shared
    > with any third party. The lenders shown are entirely fictional.

    Applicable regulatory frameworks that a production version of this product would need to
    address include:

    - **GDPR** (EU 2016/679) — data minimisation, consent, right to explanation for automated decisions
    - **PSD2** (EU 2015/2366) — licensed access to payment account data
    - **EU AI Act** — high-risk AI system classification for credit scoring
    - **CRD IV / CRR** — capital requirements for lending institutions
    - **MiFID II** — if investment products are involved
    """
)
