"""Methodology, data, scoring model, and limitations."""

import streamlit as st

from pages.components.shared_styles import inject_shared_styles

st.set_page_config(page_title="Methodology — ForkFund", layout="wide")
inject_shared_styles()

st.title("Methodology")
st.caption(
    "This page describes how ForkFund generates credit assessments, "
    "what the scores mean, and the boundaries of this prototype."
)

st.markdown("---")

# ── Three-column intro ────────────────────────────────────────────────────────
c1, c2, c3 = st.columns(3)

with c1:
    st.subheader("What this tool does")
    st.markdown("""
ForkFund produces a structured pre-underwriting profile for restaurant businesses,
combining simulated open-banking, POS, accounting, and company-registration data
into a single scored document — the Restaurant Credit Passport.

The output is intended as decision-support for lending officers, not as a substitute
for full credit underwriting.
    """)

with c2:
    st.subheader("What it does not do")
    st.markdown("""
ForkFund does not make credit decisions, approve loans, or predict default probability.
It does not connect to live financial systems or hold real customer data.
The scoring model has not been validated against historical repayment outcomes,
and the weights are illustrative rather than actuarially calibrated.
    """)

with c3:
    st.subheader("Prototype status")
    st.markdown("""
This is a student MVP built for demonstration purposes. All restaurant, transaction,
and lender data is computer-generated (synthetic). No real business records,
bank accounts, or government data are used. Scores carry no predictive validity
for real businesses.
    """)

st.markdown("---")

# ── Scoring model ─────────────────────────────────────────────────────────────
st.subheader("Scoring Model")

st.markdown("""
The composite score (0–100) is a weighted average of seven independently
normalised dimensions. Each dimension is scaled to [0, 100] before weighting.
""")

col_table, col_note = st.columns([2, 1])

with col_table:
    st.markdown("""
| Dimension | Weight | Data source | Method |
|---|---|---|---|
| Revenue stability | 20% | POS | 1 – coefficient of variation across monthly net revenue |
| Cash-flow strength | 20% | PSD2 | Net inflow margin normalised to a 30% benchmark |
| Debt burden | 15% | Accounting | 1 – (debt / revenue), capped at zero |
| Repayment capacity | 15% | Accounting | EBITDA margin normalised to a 30% benchmark |
| Cost structure | 10% | Accounting | Linear scale from 45% cost ratio (100) to 85% (0) |
| Business maturity | 10% | KvK | Years since registration, capped at 10 years |
| Data completeness | 10% | All | Fraction of the four sources that are populated |
""")

with col_note:
    st.markdown("""
<div class="ff-card-inset">
  <strong style="font-size:12px;">Grade bands</strong><br><br>
  <span style="font-size:12px;line-height:1.9;display:block;">
    A &nbsp;≥ 80<br>
    B &nbsp;65 – 79<br>
    C &nbsp;50 – 64<br>
    D &nbsp;35 – 49<br>
    F &nbsp;&lt; 35
  </span>
</div>
<div class="ff-card-inset" style="margin-top:8px;">
  <strong style="font-size:12px;">Risk bands</strong><br><br>
  <span style="font-size:12px;line-height:1.9;display:block;">
    Low &nbsp;&nbsp;&nbsp;&nbsp;≥ 70<br>
    Medium &nbsp;50 – 69<br>
    High &nbsp;&nbsp;&nbsp;30 – 49<br>
    Very High &lt; 30
  </span>
</div>""", unsafe_allow_html=True)

st.markdown("""
**Absent data.** When a data source is unavailable, accounting-dependent dimensions
default to a neutral score of 50 rather than 0. This reflects the absence of
information rather than a negative assessment.

**Inactive registration.** A KvK record marked inactive applies a 50% penalty
to the business maturity sub-score.
""")

st.markdown("---")

# ── Synthetic data ────────────────────────────────────────────────────────────
st.subheader("Synthetic Data")

st.markdown("""
All data used in this prototype is generated by a deterministic random process
with a fixed seed. The generator produces 120 restaurant profiles with associated
12-month transaction and POS records, three years of accounting data, and
ten fictional lender profiles.

The generation process is parameterised to produce a realistic spread of
financial health across the dataset — including operators with healthy margins,
seasonally dependent businesses, highly leveraged profiles, and cases of
operational distress. Statistical distributions were calibrated to produce
the score diversity described below, not to match any published industry benchmark.
""")

col_data, _ = st.columns([2, 1])
with col_data:
    st.markdown("""
| Dataset | Records | Description |
|---|---|---|
| Restaurants | 120 | Master profile per business |
| Transactions | ~88,000 | 12-month simulated bank transaction history |
| POS records | ~44,000 | Daily cover and revenue records |
| Accounting | 360 | Annual P&L and balance sheet (3 years per business) |
| Lenders | 10 | Fictional lender profiles with stated criteria |
""")

st.markdown("---")

# ── Simulated integrations ────────────────────────────────────────────────────
st.subheader("Simulated Integrations")

st.markdown("""
The Data Connection step simulates the consent and authorisation flows that
real integrations would require. No network requests are made.
""")

st.markdown("""
| Source | Real-world equivalent | What this prototype uses |
|---|---|---|
| Open Banking (PSD2) | Tink, Nordigen, Salt Edge | Synthetic transaction CSV filtered by restaurant |
| POS System | Square, Lightspeed, Untill | Synthetic daily revenue CSV |
| Accounting | Exact, Twinfield, Moneybird | Synthetic P&L and balance sheet CSV |
| KvK | Dutch Chamber of Commerce API | Synthetic company registration CSV |
""")

st.markdown("---")

# ── Limitations ───────────────────────────────────────────────────────────────
st.subheader("Known Limitations")

st.markdown("""
**Model validity.** Score weights are illustrative starting values.
They were not derived from historical default or repayment data and have not
been backtested against real credit outcomes.

**Single accounting year.** The scoring engine uses only the most recent
accounting year for debt burden, repayment capacity, and cost structure.
A production model would use year-on-year trend analysis.

**No revenue seasonality detection.** The coefficient-of-variation approach
treats all monthly revenue variance as instability, without distinguishing
between predictable seasonal patterns and structural volatility.

**Data completeness is binary per source.** A source with one record is treated
identically to one with 700. A production implementation would weight sources
by record density and recency.

**Session persistence.** There is no database. All state is held in the browser
session and is lost on page refresh. This is an intentional MVP constraint.

**Lender dataset.** The ten fictional lenders cover a limited range of criteria.
Some restaurant profiles will return zero eligible lenders — particularly
distressed profiles — which is an accurate reflection of their eligibility,
not a tool defect.
""")

st.markdown("---")

# ── Regulatory context ────────────────────────────────────────────────────────
st.subheader("Regulatory Context")

st.markdown("""
A production version of this product would need to address the following
regulatory frameworks, among others:

- **GDPR (EU 2016/679):** Data minimisation, consent, and the right to a
  meaningful explanation for automated credit-related decisions (Article 22).
- **PSD2 (EU 2015/2366):** Licenced Third-Party Provider status required for
  access to payment account data.
- **EU AI Act:** Credit-scoring systems may be classified as high-risk AI
  under Article 6, requiring conformity assessments and human oversight.
- **CRD IV / CRR:** Capital requirements applying to licenced lenders.

ForkFund in its current form does not satisfy any of these requirements.
It is a demonstration prototype, not a production financial service.
""")
